@url = http://localhost:8080


###
GET {{url}}/users/6571d83d43119182a6098b94

###
GET {{url}}/users/email/2334

###
POST {{url}}/users

{
    "email" : "test@test11.com",
	"password": "123456!11",
	"name": "Teste name11",
	"age": 34
}

###
PUT {{url}}/users/657225332c3e435fc3f413f1

{
	"name": "Teste name8",
	"age": 38
}

###
DELETE {{url}}/users/6571d8ab43119182a6098b95